#!/opt/pwn.college/python

import ast

def check_filename(filename):
    #expected output of checked file contents
    expected_output = "Hello World!"

    try:
        # Read the contents of the file

        with open(filename, 'r') as file:
            user_code = file.read()

        # Parse the code
        parsed_code = ast.parse(user_code)

        # Redirects the output for comparison
        from io import StringIO
        import sys

        old_stdout = sys.stdout
        sys,stdout - StringIO()

        # Execute the users code
        exec(user_code)        

        # Capture the output of the executed program
        output = sys.stdout.getvalue().strip()

        # Checks if the output matches the expected output
        if output == expected_output:
		with open("/flag") as f:
                flag = f.read().strip()
            print(f"Congratulations! Here is your flag: {flag}")
        else:
            print("Error: There was an issue with your code. {str(e)}")


if __name__ == "__main__"
    filename = "hello_world.py"
    check_filename(filename)
